

server.port=8091
spring.application.name=codigoms-pagos

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL del microservicio de ordenes
orders.service.url=http://localhost:8084

feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=5000
